artifact_uri: /run/media/priyanshu-first-of-his-name/New Volume/LIFE_Of_ENJOYMENT/Attention_concentration/A_C_1/Mislaneous_Process/2_Mlops/MLOPS_26th_Project_Internship_Job/Learnings/20.21.22.23.24.25/FeedBack/URI/550874142640571075/acc354eba1ba4739af99deb6fc23513c/artifacts
end_time: 1785764530203
entry_point_name: ''
experiment_id: '550874142640571075'
lifecycle_stage: active
run_id: acc354eba1ba4739af99deb6fc23513c
run_name: aged-sheep-343
run_uuid: acc354eba1ba4739af99deb6fc23513c
source_name: ''
source_type: 4
source_version: ''
start_time: 1785764525285
status: 3
tags: []
user_id: 7bb3d01940ec2dd31e8a67391bc3208cf8fea567
